FROM node:18.17.0 AS base

# 1. Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy root package.json and lockfile
COPY ../package.json ./
COPY ../yarn.lock ./

# Copy the docs package.json
COPY apps/website/package.json ./apps/website/package.json

# Copy app source
COPY .. .


# install dependencies
RUN npm i


# Configure database
RUN npm run prisma-generate

RUN npm run seed

# Run app
RUN npm run start


